// Tests
console.log(checkBrackets('1)()(())2(()')); // 2
console.log(checkBrackets(NaN)); // -1
console.log(checkBrackets(null)); // -1
console.log(checkBrackets(undefined)); // -1
console.log(checkBrackets(123)); // -1
console.log(checkBrackets(true)); // -1
console.log(checkBrackets(false)); // -1
console.log(checkBrackets({})); // -1
console.log(checkBrackets([])); // -1
console.log(checkBrackets('()')); // 0
console.log(checkBrackets('(())')); // 0
console.log(checkBrackets('((()))')); // 0
console.log(checkBrackets('(()()()())')); // 0
console.log(checkBrackets('(())()')); // 0
console.log(checkBrackets('()()')); // 0
console.log(checkBrackets('((())))')); // 1
console.log(checkBrackets('())')); // 1
console.log(checkBrackets('(()')); // 1
console.log(checkBrackets('(()(()')); // 1
console.log(checkBrackets('())(')); // 1
